// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.firebears.betaTestRobot2;

import org.firebears.util.CANTalon;

import edu.wpi.first.wpilibj.I2C;
import edu.wpi.first.wpilibj.I2C.Port;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
	public static final int MOTOR_CAN_ID = 2;
	public static final int ARDUINO_I2C_ADDRESS = 4;

	public static I2C arduinoI2c;

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	public static SpeedController boardmotor;

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	public static void init() {
		boardmotor = new CANTalon(MOTOR_CAN_ID);
		LiveWindow.addActuator("Board", "motor", (CANTalon) boardmotor);
		Robot.report.addCAN(MOTOR_CAN_ID, "Main motor", boardmotor);

		arduinoI2c = new I2C(Port.kOnboard, ARDUINO_I2C_ADDRESS);
		Robot.report.addOtherConfig(ARDUINO_I2C_ADDRESS, "Arduino I2C address");
	}
}
