// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.firebears.betaTestRobot2;

import org.firebears.betaTestRobot2.commands.ClearFaultsCommand;
import org.firebears.util.CANTalon;

import edu.wpi.first.wpilibj.I2C;
import edu.wpi.first.wpilibj.I2C.Port;
import edu.wpi.first.wpilibj.PowerDistributionPanel;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
	public static final boolean DEBUG = true;
	
	public static final int MOTOR_CAN_ID = 2;
	public static final int ARDUINO_I2C_ADDRESS = 4;

	public static I2C arduinoI2c;

	public static CANTalon boardmotor;

	public static void init() {
		boardmotor = new CANTalon(MOTOR_CAN_ID);
		boardmotor.setName("Board", "motor");
		LiveWindow.add(boardmotor);
		Robot.report.addCAN(MOTOR_CAN_ID, "Main motor", boardmotor);

		arduinoI2c = new I2C(Port.kOnboard, ARDUINO_I2C_ADDRESS);
		Robot.report.addOtherConfig(ARDUINO_I2C_ADDRESS, "Arduino I2C address");
		
        SmartDashboard.putData("Clear Faults", new ClearFaultsCommand(new PowerDistributionPanel(), boardmotor));
	}
}
